### ISSUE TITLE
Challenge updates

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/Python-Intermediate-Pilot#1]
- Need to choose between ideas in challenge 1-3 (conditionals)
- Need to choose between ideas in challenge 1-5 (functions for dataframes) 
- Need to discuss draft challenge 2-5 (for-loops & visualization)

**Comment by pssachdeva** [comment]
Some initial thoughts on Notebook 1, Challenge 3:

- I am in general averse to using `input` in challenges, as this is something that almost no one will ever do in a research context (and likely other contexts).
- The first idea is good, but it would be good to have something more contextual for the task. Maybe assigning labels to each, as detailed in this [document](https://www.un.org/en/development/desa/policy/wesp/wesp_current/2014wesp_country_classification.pdf). You could even turn this into a dictionary (keys-> countries, values->classification).

**Comment by pssachdeva** [comment]
Notebook 1, challenge 5:

There's only one idea here. I don't really understand the plot. But if the goal is to have a function, you could have a function plot life expectancy over years, with the input being a dataframe and a country. e.g., `plot_life_exp_country(country)` outputs a plot of `country`'s life expectancy over time, as a line plot. Then, you can loop over some random subset of countries, and create a comparison plot. It will combine both loops and functions.

**Comment by pssachdeva** [comment]
Notebook 1, challenge 5:

I definitely like the second idea more. Since this is now Python Intermediate, I feel totally comfortable having people attempt to use `apply()`. Replacing with some category as mentioned a couple comments above (e.g., "High Income") would make it more domain relevant.
